### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kevinctofel** [willjw3/gatsby-starter-developer-diary#24]
Love the theme; using it on a personal blog as I (begrudgingly) use WP for my business site.

Noticed that from the home page, I can go to the next page, i.e.: ...url/2 but when I go to the next page again, the browser tries to load ...url/2/3 and returns a 404. 

I'm going to take a look into it (I'm a n00b but at least I was able to figure out an 800px breakpoint for responsive images - yay!) but wanted to mention. Could be something I've configured incorrectly, of course. Cheers!

**Comment by kevinctofel** [comment]
Looks like I have a fix.

Line 18 of post-list.js:    const nextPage = "/" + (currentPage + 1).toString()

I now have all four pages available through next-page, next-page, etc...

Previous pages on those show a similar issue, so will work and that; if I can test and deploy the fix on my site, I'll fork and make my changes..... Cheers!

**Comment by kevinctofel** [comment]
These 2 lines in post-list.js appear to fix the issue for me.

17    const prevPage = currentPage - 1 === 1 ? "/" : "/" + (currentPage - 1).toString()
18    const nextPage = "/" + (currentPage + 1).toString()

Hope that helps; since this isn't a feature contribution, I figured to just pass along here for your consideration. Cheers!

**Comment by willjw3** [comment]
@kevinctofel Thanks for pointing that out. I don't know how I missed putting the leading slash in considering that it's what is normally done when creating a path for a link. If you'd like to submit a PR under the label bug, I'd be happy to merge it so that you can be labeled as a contributor. Maybe, though, rather than using concatenation, using a template literal might be smoother. If you'd rather not, that's OK; it'll get fixed either way. 
Let me know.

**Comment by kevinctofel** [comment]
I couldn't apply a label; could be that I have a Git account under the free student plan. Also, we learn about template literals this week in class, so I proposed concatenation. If template literal is the better approach please make it so. No need for us to do this twice. Cheers!
